배열 (Array) 구조 이해

In [ ]:
l = [[1,2,3],[4,5,6]]
type(l)

list

In [ ]:
l[0]

[1, 2, 3]

In [ ]:
l[1]

[4, 5, 6]

In [ ]:
# 리스트 내의 리스트 검색

for i, a in enumerate(l):
  for j, b in enumerate(a):
    print(l[i][j])

# enumerate를 사용해서 인덱스 정보도 함께 가져옴

1
2
3
4
5
6


In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [ ]:
np.ndarray.__dict__

mappingproxy({'__new__': <function ndarray.__new__(*args, **kwargs)>,
              '__repr__': <slot wrapper '__repr__' of 'numpy.ndarray' objects>,
              '__str__': <slot wrapper '__str__' of 'numpy.ndarray' objects>,
              '__lt__': <slot wrapper '__lt__' of 'numpy.ndarray' objects>,
              '__le__': <slot wrapper '__le__' of 'numpy.ndarray' objects>,
              '__eq__': <slot wrapper '__eq__' of 'numpy.ndarray' objects>,
              '__ne__': <slot wrapper '__ne__' of 'numpy.ndarray' objects>,
              '__gt__': <slot wrapper '__gt__' of 'numpy.ndarray' objects>,
              '__ge__': <slot wrapper '__ge__' of 'numpy.ndarray' objects>,
              '__iter__': <slot wrapper '__iter__' of 'numpy.ndarray' objects>,
              '__add__': <slot wrapper '__add__' of 'numpy.ndarray' objects>,
              '__radd__': <slot wrapper '__radd__' of 'numpy.ndarray' objects>,
              '__sub__': <slot wrapper '__sub__' of 'numpy.ndarray' objects>,


In [ ]:
# 다차원 배열 클래스

for i in dir(np.ndarray):
  if not i.startswith("_"):
    if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
      print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [ ]:
l = [1,2,3,4]
a = np.array(l)
a

array([1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
t = (1,2,3,4)
b = np.array(t)
type(b)

numpy.ndarray

In [ ]:
a.data

In [ ]:
a.data.obj

array([1, 2, 3, 4])

In [ ]:
type(a.data.obj)

numpy.ndarray

In [ ]:
e = np.array(l,dtype=np.float64) # 형 변환
e

array([1., 2., 3., 4.])

In [ ]:
e.dtype

dtype('float64')

In [ ]:
a2 = np.array([[1,2,3],[4,5,6]])
a2.shape

(2, 3)

In [ ]:
a2.ndim

2

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
a2.itemsize # 하나의 원소 크기

8

In [ ]:
a2.size # 전체 원소 개수

6

In [ ]:
a2.strides # 원소와 하나의 행의 바이트 크기

(24, 8)

In [ ]:
# 다차원 배열

np.ndarray.__bases__ # ndarray : 다차원 가능

(object,)

In [ ]:
np.matrix.__bases__ # matrix : 2차원만 가능

(numpy.ndarray,)

넘파이 모듈 함수 특징

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
(a != 0).any

<function ndarray.any>

In [ ]:
np.any

<function any at 0x78593ef21cb0>

In [ ]:
np.ndarray.any is np.core.fromnumeric.any

False

In [ ]:
np_ = set(dir(np))

In [ ]:
np_

{'ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_core',
 '_distributor_init',


In [ ]:
# 같은 이름의 함수와 메서드
nd_ = set(dir(np.ndarray))

In [ ]:
npd_ = np_ & nd_

In [ ]:
len(npd_)

48

In [ ]:
count = 0

for i in list(npd_):
  count += 1
  print(i, end = " ")
  if count % 5 == 0:
    print()

nbytes dot ptp any compress 
cumprod max __dir__ argmax argsort 
reshape all shape imag sum 
real mean nonzero put conj 
cumsum diagonal trace take partition 
repeat size conjugate transpose ndim 
argpartition var clip resize dtype 
prod std swapaxes argmin copy 
sort __doc__ ravel min choose 
round searchsorted squeeze 

In [ ]:
# 유니버셜 함수

a = dir(np)
np.ufunc

# 넘파이 특징은 반복문을 사용하지 않는 계산입니다.
# 이런 기능을 벡터화 연산이라고하며 이를 지원하는 함수가 유니버셜 함수

numpy.ufunc

In [ ]:
count = 0

for i in a:
  if i == "Tester":
    continue
  if type(np.__dict__[i]) == np.ufunc:
    print(i, end = " ")
    count += 1
    if count % 5 == 0:
      print()

abs absolute add arccos arccosh 
arcsin arcsinh arctan arctan2 arctanh 
bitwise_and bitwise_not bitwise_or bitwise_xor cbrt 
ceil conj conjugate copysign cos 
cosh deg2rad degrees divide divmod 
equal exp exp2 expm1 expm1x 
fabs float_power floor floor_divide fmax 
fmin fmod frexp gcd greater 
greater_equal heaviside hypot invert isfinite 
isinf isnan isnat lcm ldexp 
left_shift less less_equal log log10 
log1p log2 logaddexp logaddexp2 logical_and 
logical_not logical_or logical_xor matmul maximum 
minimum mod modf multiply negative 
nextafter not_equal positive power rad2deg 
radians reciprocal remainder right_shift rint 
sign signbit sin sinh spacing 
sqrt square subtract tan tanh 


KeyError: 'testing'

In [ ]:
# 벡터화 연산

a = np.arange(6,10)
a

array([6, 7, 8, 9])

In [ ]:
b = np.arange(10,14)
b

array([10, 11, 12, 13])

In [ ]:
c = a*b
c

array([ 60,  77,  96, 117])

In [ ]:
# 축 연산
a2 = np.array([1,2,3,4])
a2

array([1, 2, 3, 4])

In [ ]:
a2 = a2.reshape(2,2)
a2

array([[1, 2],
       [3, 4]])

In [ ]:
np.sum(a2)

10

In [ ]:
np.sum(a2, axis = 0)

array([4, 6])

In [ ]:
np. sum(a2, axis=1)

array([3, 7])

In [ ]:
# 배열의 원소 개수 일치

a = np.array([4,5])
a.shape

(2,)

In [ ]:
b = np.array([3,4,5])
b.shape

(3,)

In [ ]:
try:
  a+b
except Exception as e:
  print(e)

operands could not be broadcast together with shapes (2,) (3,) 


배열 할당과 검색

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = a
b

array([[1, 2],
       [3, 4]])

In [ ]:
b[0] = 999
b

array([[999, 999],
       [  3,   4]])

In [ ]:
a # 다차원 배열을 다른 변수에 할당하면 공유 -> 특정 원소 갱신하면 원본 갱신

array([[999, 999],
       [  3,   4]])

In [ ]:
# 배열의 복사/ 뷰 확인

f = np.array([4,5,6,7,8])
e = f.copy()
e

array([4, 5, 6, 7, 8])

In [ ]:
g = f[:] # 모든 원소
g

array([4, 5, 6, 7, 8])

In [ ]:
g.base

array([4, 5, 6, 7, 8])

In [ ]:
np.may_share_memory(g,f)

True

In [ ]:
# 리스트 검색
l = list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
index = 1
l.__getitem__(index) # 인덱스 1번째의 데이터

2

In [ ]:
index = slice(1,3)
l.__getitem__(index)

[2, 3]

In [ ]:
# 다차원 배열 검색

a = np.array([1,2,3,4,5,6,7])
index = 1
a.__getitem__(index)

2

In [ ]:
index = slice(1,3)
a.__getitem__(index)

array([2, 3])

In [ ]:
index = 1
a.__getitem__(index)

2

In [ ]:
index = [1]
a.__getitem__(index)

array([2])

In [ ]:
index = a< 4
index

array([ True,  True,  True, False, False, False, False])

In [ ]:
a.__getitem__(index)

array([1, 2, 3])

선형대수 기본 알아보기

In [ ]:
a = np.array(43)
type(a)

numpy.ndarray

In [ ]:
a

array(43)

In [ ]:
a.ndim

0

In [ ]:
a.shape

()

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a==43

True

스칼라와 벡터 알아보기

In [ ]:
# scalar - 0차원

a = np.array(43)
type(a)

numpy.ndarray

In [ ]:
a

array(43)

In [ ]:
a.ndim

0

In [ ]:
a.shape

()

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a == 43

True

In [ ]:
# vector - 1차원

v = np.array([43])
type(v)

numpy.ndarray

In [ ]:
v

array([43])

In [ ]:
v.ndim

1

In [ ]:
v.shape

(1,)

In [ ]:
# 벡터 생성 함수

v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
v.dtype

dtype('int64')

In [ ]:
v1 = np.arange(10.5, 20.5, 0.5)

In [ ]:
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [ ]:
v1.dtype

dtype('float64')

In [ ]:
v1.size

20

In [ ]:
la = np.linspace(1,10,10)
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
la.dtype

dtype('float64')

In [ ]:
la1 = np.linspace(1,10,10,endpoint=False, retstep = True)
la1

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [ ]:
lo = np.logspace(0,2,4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [ ]:
la2 = np.linspace(0,2,4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [ ]:
for i in la2:
  print(np.power(10,i))

1.0
4.641588833612778
21.544346900318832
100.0


In [ ]:
# 벡터 크기

v = np.arange(3,5)
v

array([3, 4])

In [ ]:
v_p = np.power(v,2)
v_r = np.sqrt(np.sum(v_p))
v_r

5.0

In [ ]:
np.hypot(v[0],v[1])

5.0

In [ ]:
np.linalg.norm(v)

5.0

In [ ]:
# 표준 단위 벡터

e1= np.array([1,0,0])
np.linalg.norm(e1)

1.0

In [ ]:
e2 = np.array([0,1,0])
np.linalg.norm(e2)

1.0

In [ ]:
e3 = np.array([0,0,1])
np.linalg.norm(e3)

1.0

In [ ]:
# 단위 벡터

v_3 = np.array([1,2,3])
v_3_n = np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [ ]:
v_3_u = v_3 / v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [ ]:
np.linalg.norm(v_3_u)

1.0

In [ ]:
# 벡터의 상등

a = np.arange(3,5)
b = np.arange(3,5)
np.array_equal(a,b)

True

In [ ]:
a_1 = np.linalg.norm(a)
b_1 = np.linalg.norm(b)

In [ ]:
a_1 == b_1

True

In [ ]:
# 벡터의 거리

c = np.arange(10,13)
d = np.arange(0,3)
np.sqrt(np.sum(np.square(c-d)))


17.320508075688775

In [ ]:
np.linalg.norm(c-d)

17.320508075688775

행렬 알아보기

In [ ]:
a = np.array([[43],[44]])
type(a)

numpy.ndarray

In [ ]:
a

array([[43],
       [44]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 1)

In [ ]:
# 행렬 랭크
# 선형 독립 아닌 벡터 존재
cl = np.array([[1,2,4],[2,4,8],[3,4,5]])
np.linalg.matrix_rank(cl)

2

In [ ]:
np.linalg.det(cl)

0.0

In [ ]:
cl[0] * 2 - cl[1]

array([0, 0, 0])

In [ ]:
# 모두 선형독립인 벡터

c2 = np.array([[1,3,4],[1,8,5],[2,3,4]])
np.linalg.matrix_rank(c2)

3

In [ ]:
np.linalg.det(c2)

-17.0

In [ ]:
np.linalg.matrix_rank(c2.T)

3

In [ ]:
# 축 알아보기
a = np.array([[2,3],[4,5]])
a.sum() # 행렬 전체 sum

14

In [ ]:
a.sum(axis = 0)

array([6, 8])

In [ ]:
a.sum(axis= 1)

array([5, 9])

In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
c.ndim

3

In [ ]:
c.shape

(2, 2, 2)

In [ ]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
c[0]

array([[1, 2],
       [3, 4]])

In [ ]:
c[1]

array([[5, 6],
       [7, 8]])

In [ ]:
c.sum(axis = 0) # 같은 행

array([[ 6,  8],
       [10, 12]])

In [ ]:
c.sum(axis = 1) # 열

array([[ 4,  6],
       [12, 14]])

In [ ]:
c.sum(axis = 2) # 행

array([[ 3,  7],
       [11, 15]])

In [ ]:
# 확장 및 축소

# 차원 확장
x = np.array([1,2])
x

array([1, 2])

In [ ]:
y = np.expand_dims(x,axis=1)
y

array([[1],
       [2]])

In [ ]:
z = np.expand_dims(x,axis = 0)
z

array([[1, 2]])

In [ ]:
# 차원 축소

x = np.array([[1,4,5],[4,5,6],[7,8,9]])
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [ ]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

논리식 검색과 팬시 검색

In [ ]:
L =np.random.randn(7,4) # randn ~ N(0,1) 을 7x4로 표현
L

array([[-1.89103823, -0.87373166,  0.33599145, -1.44734929],
       [ 1.08171377, -0.01478073,  0.74810514,  0.14991337],
       [-1.74181959, -0.19339137,  0.14162752, -0.23062825],
       [-1.1350341 ,  1.55991131,  0.27633741, -1.3753703 ],
       [ 0.65923849,  0.36744648,  1.21558054, -0.05241887],
       [-0.19847238,  0.16880216,  2.12460945, -2.04024383],
       [-0.16246107, -1.15781279, -1.57074859, -1.52284869]])

In [ ]:
L[L<0]

array([-1.89103823, -0.87373166, -1.44734929, -0.01478073, -1.74181959,
       -0.19339137, -0.23062825, -1.1350341 , -1.3753703 , -0.05241887,
       -0.19847238, -2.04024383, -0.16246107, -1.15781279, -1.57074859,
       -1.52284869])

In [ ]:
L[L<0] = 999
L

array([[9.99000000e+02, 9.99000000e+02, 3.35991449e-01, 9.99000000e+02],
       [1.08171377e+00, 9.99000000e+02, 7.48105142e-01, 1.49913367e-01],
       [9.99000000e+02, 9.99000000e+02, 1.41627518e-01, 9.99000000e+02],
       [9.99000000e+02, 1.55991131e+00, 2.76337415e-01, 9.99000000e+02],
       [6.59238491e-01, 3.67446483e-01, 1.21558054e+00, 9.99000000e+02],
       [9.99000000e+02, 1.68802157e-01, 2.12460945e+00, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02]])

In [ ]:
LC = L[L==999]
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999., 999., 999., 999., 999.])

In [ ]:
# 논리 검색에 주의할 점은 and, or, not 연산을 사용하지 못합니다. 대신 logical_and 등의 함수를 사용

L = np.arange(0,12)
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
try:
  L and L
except Exception as e:
  print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [ ]:
np.logical_and(L,L)

array([ True, False, False, False, False, False, False, False, False,
       False, False, False])

In [ ]:
np.logical_or(L,L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
np.logical_not(L,L)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
L[np.logical_and(L,L)]

array([1])

In [ ]:
# 펜시 검색

x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
pos2 = np.array([1,2,2,2])
x[pos2]

array([2, 3, 3, 3])

In [ ]:
c = x[pos2]
c

array([2, 3, 3, 3])

In [ ]:
np.may_share_memory(x,c)

False

In [ ]:
y= x[:4]
y

array([1, 2, 3, 4])

In [ ]:
np.may_share_memory(x,y)

True

In [ ]:
# 행과 열을 전부 리스트로 전달할 경우는 두 리스트의 쌍으로 구성해서 배열의 원소 표시
# -> np.ix_ 함수로 처리

x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
x[[3,0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [ ]:
x[[3][0]]

array([12, 13, 14, 15])

In [ ]:
a = np.array([[2,3,4,5],[8,9,0,1]])
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [ ]:
type(np.ix_)

numpy._ArrayFunctionDispatcher

In [ ]:
a[np.ix_([0,1],[0,1])]

array([[2, 3],
       [8, 9]])

In [ ]:
# 팬시 검색 혼용
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
x[0,[0,1]]

array([0, 1])

In [ ]:
x[1,[0,1]]

array([5, 6])

In [ ]:
x[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
x[[0,1],0]

array([0, 5])

In [ ]:
a = x[[0,1],0]
a

array([0, 5])

In [ ]:
np.may_share_memory(a,x)

False

In [ ]:
# 팬시 검색을 이용한 축소 및 확대

# 배열보다 작게 조회

x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a = x[1:,1:]
a

array([[4, 5],
       [7, 8]])

In [ ]:
np.may_share_memory(a,x)

True

In [ ]:
# 배열보다 크게 조회

a = np.reshape(np.arange(10),(2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
c = a[[1,1,1], np.newaxis]  # [1,1,1]은 인덱스 리스트로 a[1]은 1행 의미 -> 1행 3번 선택
c

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

In [ ]:
c.shape

(3, 1, 5)

메소드나 함수로 검색하기

In [ ]:
# 다차원 배열의 메소드인 item, view를 사용해서 검색이 가능하고 itemset으로 내부 원소 갱신 가능

x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x.item(1)

1

In [ ]:
x.item(5)

5

In [ ]:
x.item(1,2)

5

In [ ]:
x.item((2,2))

8

In [ ]:
x.itemset(2,20) # 갱신
x

array([[ 0,  1, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [ ]:
x.itemset((1,2),20)
x

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [ ]:
x.view()

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [ ]:
# take 메소드로 검색하고 put 메소드로 내부 원소 변경

b = np.linspace(1,10,10).reshape(2,5)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
pos1 = [3,4]
b.take(pos1)

array([4., 5.])

In [ ]:
pos2 = [[0,1],[3,4]]
b.take(pos2)

array([[1., 2.],
       [4., 5.]])

In [ ]:
c = b.copy()
np.may_share_memory(b,c)

False

In [ ]:
c.put(pos1, 30)
c

array([[ 1.,  2.,  3., 30., 30.],
       [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
c.put(pos1, 50)
c

array([[ 1.,  2.,  3., 50., 50.],
       [ 6.,  7.,  8.,  9., 10.]])

In [ ]:
# 질의 함수
# 넘파이 함수 choose는 인덱스로 검색

x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.choose(0,x) # np.choose(choices, arrays)

array([0, 1, 2])

In [ ]:
np.choose([0],x)

array([0, 1, 2])

In [ ]:
np.choose(tuple([0,1,2]), x) # x의 각 행에서 해당 위치 값 선택

array([0, 4, 8])

In [ ]:
np.choose(tuple([2,1,0]),x)

# 첫 번째 열에서는 세번째 행 -> [2],[0]
# 두 번째 열에서는 두번째 행 -> [1],[1]
# 세 번째 열에서는 첫번째 행 -> [0],[2]

array([6, 4, 2])

In [ ]:
# 넘파이 where은 조건식 판단을 검색에 넣어서 조회 가능 -> select, extract

np.where(x>4) # 조건 만족하는 인덱스 찾음

# 2차원에서는 앞의 array는 axis = 0, 뒤의 array는 axis = 1에 해당
# -> [1,2],[2,0],[2,1],[2,2]

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [ ]:
a = np.select(x>5, x*2) # 앞의 조건에서 만족한 것들을 대상으로 적용할 값
a

array([12, 14, 16])

In [ ]:
np.extract(x>4, x)

array([5, 6, 7, 8])

브로드캐스팅

In [ ]:
x = np.arange(10).reshape(2,5)
y = np.arange(5)

In [ ]:
z = np.broadcast(x,y)
z

In [ ]:
z.shape, z.ndim

((2, 5), 2)

In [ ]:
for i in z:
  print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 0)
(6, 1)
(7, 2)
(8, 3)
(9, 4)


In [ ]:
x+y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [ ]:
# 브로드캐스팅 처리 규칙
x2 = np.ones((2,3)) # 다 1로 채움
x2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x1 = np.ones(3)
x1

array([1., 1., 1.])

In [ ]:
x1.shape, x2.shape

((3,), (2, 3))

In [ ]:
x1.shape[0] == x2.shape[1]

True

In [ ]:
# 차원 추가
x1 = x1[np.newaxis,]
x1.shape

(1, 3)

In [ ]:
# 행 하나 더 추가
x1 = np.vstack((x1[0], x1[0]))
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x1.shape == x2.shape

True

In [ ]:
x1 + x2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
# 행벡터와 열벡터 브로드캐스팅 확장

x = np.arange(1,4)
x

array([1, 2, 3])

In [ ]:
x.shape , x.ndim

((3,), 1)

In [ ]:
x1 = x.reshape(1,3)
x1

array([[1, 2, 3]])

In [ ]:
x2 = x[np.newaxis,]
x2

array([[1, 2, 3]])

In [ ]:
x2.shape , x2.ndim

((1, 3), 2)

In [ ]:
y = np.arange(1,4)
y

array([1, 2, 3])

In [ ]:
y.shape , y.ndim

((3,), 1)

In [ ]:
y1 = y.reshape(3,1)
y1

array([[1],
       [2],
       [3]])

In [ ]:
y2 = y[:, np.newaxis]
y2

array([[1],
       [2],
       [3]])

In [ ]:
y2.shape , y2.ndim

((3, 1), 2)

In [ ]:
np.broadcast_arrays(x1,y1)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [ ]:
x1 + y1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

행렬의 연산

In [3]:
# 벡터의 내적

a = np.array([3,4])
b = np.array([5,6])
a@b

39

In [4]:
np.dot(a,b)

39

In [5]:
np.inner(a,b)

39

In [6]:
# 벡터의 외적

a = np.array([1,4])
b = np.array([3,6])
np.cross(a,b)

array(-6)

In [3]:
c = np.array([1,4,3])
d = np.array([3,4,5])
np.cross(c,d)

array([ 8,  4, -8])

행렬식, 역행렬 처리

In [4]:
# 행렬식

a = np.array([[3,1],[2,2]])
np.linalg.det(a)

4.000000000000001

In [6]:
np.allclose(4.0, np.linalg.det(a))

True

In [7]:
# 역행렬

a = np.array([[3,2],[6,4]])
np.linalg.det(a)

0.0

In [8]:
b = np.array([[1,2,3],[4,5,6],[3,2,4]])
np.linalg.det(b)

-9.000000000000002

In [10]:
bi = np.linalg.inv(b)
bb = np.dot(b,bi)

In [11]:
np.allclose(np.eye(3),bb)

True

다차운 배열의 구조 변경

In [12]:
# 배열의 형상 변경

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
x1 = x.reshape(2,8)
x1

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [14]:
y1 = x.reshape(4,-1)
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
# 베열의 크기 변경

a = np.arange(4)
a

array([0, 1, 2, 3])

In [16]:
np.resize(a,8)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [17]:
np.append(a,a)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [18]:
b = np.arange(4)
b.resize(4,4)
b

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
c = np.arange(8)
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
c.resize(4, refcheck=False) # 배열이 참조되고 있는 다른 곳이 있는지 확인

In [22]:
c

array([0, 1, 2, 3])

In [27]:
# 1차원 배열을 2차원 배열로 변경

x = np.arange(3)
y = np.arange(4)

x_, y_ = np.meshgrid(x,y)

In [24]:
x_

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [25]:
y_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [28]:
x_1 = x.reshape(1,-1)
x_1

array([[0, 1, 2]])

In [29]:
np.concatenate([x_1,x_1, x_1, x_1])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [30]:
y_1 = y.reshape(-1,1)
y_1

array([[0],
       [1],
       [2],
       [3]])

In [31]:
np.concatenate([y_1, y_1,y_1,y_1], axis = 1)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [32]:
np.broadcast_arrays(np.arange(10,30,10).reshape(2,1), np.arange(1,5).reshape(1,4))

[array([[10, 10, 10, 10],
        [20, 20, 20, 20]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [33]:
a,b = np.mgrid[10:30:10, 1:5] # 둘 다 행벡터

In [34]:
a

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [35]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [36]:
c,d = np.ogrid[10:30:10, 1:5]

In [39]:
c # 열벡터

array([[10],
       [20]])

In [38]:
d # 행벡터

array([[1, 2, 3, 4]])

In [40]:
e,f = np.broadcast_arrays(c,d)

In [41]:
e

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [42]:
f

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [43]:
# 축이 1인 차원 줄이기

x = np.array([[[0],[1],[2]]])
x

array([[[0],
        [1],
        [2]]])

In [44]:
x.shape

(1, 3, 1)

In [45]:
y = np.array([[0],[1],[2]])
y

array([[0],
       [1],
       [2]])

In [46]:
y.shape

(3, 1)

In [47]:
np.squeeze(x)

array([0, 1, 2])

In [49]:
np.squeeze(x).shape

(3,)

In [50]:
np.squeeze(x, axis = 0) # 외부 차원 축소

array([[0],
       [1],
       [2]])

In [52]:
np.squeeze(x, axis = 2) # 내부 차원 축소

array([[0, 1, 2]])

In [53]:
# 내부 원소로 배열 확대
# 원소 반복해서 증가하는 repeat 함수 사용

a = np.linspace(1,5,5, dtype = np.int32)
a

array([1, 2, 3, 4, 5], dtype=int32)

In [54]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5], dtype=int32)

In [55]:
e = np.arange(4).reshape(2,2)
e

array([[0, 1],
       [2, 3]])

In [56]:
# 주어진 배열 크기 확대하는 tile 함수 사용
np.tile(e,2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [57]:
# 배열 분리
a = np.linspace(1,6,6,dtype=np.int32).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [58]:
b = np.vstack([a,a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [59]:
# 큰 배열을 작은 배열로 분리해서 계산
x,y = np.split(b,[2]) # 2개로 분리

In [60]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [61]:
y

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [62]:
# 배열 쌓기 객체 -> r_,c_ 사용

a = np.arange(6).reshape(2,3)

In [63]:
c = np.random.randn(2,3)

In [64]:
np.r_[a,c] # 행방향 쌓음

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [ 0.44897062, -0.42822937,  1.09553654],
       [-1.10660719, -0.01153497, -1.15368075]])

In [65]:
np.c_[a,c] # 열방향 쌓음

array([[ 0.        ,  1.        ,  2.        ,  0.44897062, -0.42822937,
         1.09553654],
       [ 3.        ,  4.        ,  5.        , -1.10660719, -0.01153497,
        -1.15368075]])