# Tensor 이해 - 생성
- Tensor란 ? 
    - pytorch에서 데이터를 저장하는 객체
    - 모델에 입력/출력 데이터 형태 
- 개발 버전 : torch v.2.4.1

In [3]:
import torch
print(f'torch v.{torch.__version__}')

torch v.2.4.1


In [4]:
# 원하는 값으로 채운 텐서 생성 

# 함수 기능 : 텐서 속성 정보 출력 함수 

def printInfo(obj, obj_name):
    print(f'\n[{obj_name}]')
    print(f'shape : {obj.shape}')
    print(f'ndim : {obj.ndim} 차원')
    print(f'dtype : {obj.dtype}')
    print(f'device : {obj.device}')
    print(f'data : \n{obj.data}')

## 텐서 생성 [1] torch.tensor()

In [7]:
# 데이터 1개 즉, 스칼라

data_tf = torch.tensor(10)
printInfo(data_tf, 'data_tff')


data_tf = torch.tensor(10, dtype = torch.uint8) # 데이터 타입 지정 
printInfo(data_tf, 'data_tff')


[data_tff]
shape : torch.Size([])
ndim : 0 차원
dtype : torch.int64
device : cpu
data : 
10

[data_tff]
shape : torch.Size([])
ndim : 0 차원
dtype : torch.uint8
device : cpu
data : 
10


In [9]:
# 데이터 1개 즉, 벡터 1D

data_tf = torch.tensor([10])
printInfo(data_tf, 'data_tff')


data_tf = torch.tensor([10], dtype = torch.uint8) # 데이터 타입 지정 
printInfo(data_tf, 'data_tff')

data_tf = torch.tensor([]) # 데이터가 없어도 1D
printInfo(data_tf, 'data_tff')


[data_tff]
shape : torch.Size([1])
ndim : 1 차원
dtype : torch.int64
device : cpu
data : 
tensor([10])

[data_tff]
shape : torch.Size([1])
ndim : 1 차원
dtype : torch.uint8
device : cpu
data : 
tensor([10], dtype=torch.uint8)

[data_tff]
shape : torch.Size([0])
ndim : 1 차원
dtype : torch.float32
device : cpu
data : 
tensor([])


In [10]:
# 데이터 1개 즉, 행렬

data_tf = torch.tensor([[10]])
printInfo(data_tf, 'data_tff')


data_tf = torch.tensor([[10],[20]], dtype = torch.uint8) # 데이터 타입 지정 
printInfo(data_tf, 'data_tff')


[data_tff]
shape : torch.Size([1, 1])
ndim : 2 차원
dtype : torch.int64
device : cpu
data : 
tensor([[10]])

[data_tff]
shape : torch.Size([2, 1])
ndim : 2 차원
dtype : torch.uint8
device : cpu
data : 
tensor([[10],
        [20]], dtype=torch.uint8)


In [12]:
# 데이터 1개 즉, ND

data_tf = torch.tensor([[[[10]]]])
printInfo(data_tf, 'data_tff')


data_tf = torch.tensor([[[[10],[20]]]], dtype = torch.uint8) # 데이터 타입 지정 
printInfo(data_tf, 'data_tff')


[data_tff]
shape : torch.Size([1, 1, 1, 1])
ndim : 4 차원
dtype : torch.int64
device : cpu
data : 
tensor([[[[10]]]])

[data_tff]
shape : torch.Size([1, 1, 2, 1])
ndim : 4 차원
dtype : torch.uint8
device : cpu
data : 
tensor([[[[10],
          [20]]]], dtype=torch.uint8)
