# Tensor 변환 
- torch.as_tensor()
    - 동일 타입과 디바이스를 가진 데이터 존재 ==> view 즉, 데이터 공유 
    - 다른 타입 또는 다른 디바이스를 가진 데이터 존재 ==> copy 즉, 생성 
    - view tensor 또는 copy tensor 반환 

In [1]:
# 모듈 로딩 

import torch

## Python 객체 ==> Tensor 변환 

In [2]:
## List => Tensor 
data = list(range(1,10))

In [4]:
# torch.as_tensor()
data_ts = torch.as_tensor(data)
data_ts, data_ts.shape, data_ts.ndim, data_ts.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), 1, torch.int64)

In [5]:
data[0] = 100

In [7]:
data, data_ts # data_ts 는 변경사항 없음 

([100, 2, 3, 4, 5, 6, 7, 8, 9], tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

### Numpy ndarray 객체 ==> Tensor 변환

In [8]:
import numpy as np

In [11]:
arr1 = np.array([1,2,3])
arr1, arr1.dtype, arr1.ndim

(array([1, 2, 3]), dtype('int32'), 1)

In [12]:
arr_ts = torch.as_tensor(arr1)
arr_ts, arr_ts.dtype, arr_ts.ndim

(tensor([1, 2, 3], dtype=torch.int32), torch.int32, 1)

In [14]:
arr1[0] = 77
arr1, arr_ts

(array([77,  2,  3]), tensor([77,  2,  3], dtype=torch.int32))

In [15]:
arr_ts[0] = 99
arr1, arr_ts

(array([99,  2,  3]), tensor([99,  2,  3], dtype=torch.int32))

### Numpy ndarray ==> Tensor 변환 : from_numpy()

In [18]:
arr1 = np.array([5,7,9], dtype=np.float32)
arr1, arr1.data, arr1.size, arr1.itemsize

# arr1.data : 넘파이에서 데이터가 들어있는 주소 
# arr1.size : 배열 길이 
# arr1.itemsize : 데이터 하나의 크기 

print(f'데이터 저장 메모리 : {arr1.data}\n')
print(f'원소/요소 개수 : {arr1.size}\n')
print(f'원소/요소 1개 크기 : {arr1.itemsize}\n')
print(f'타입 : {arr1.dtype}\n')
print(f'방향 : {arr1.strides}')


데이터 저장 메모리 : <memory at 0x0000021943DFB880>

원소/요소 개수 : 3

원소/요소 1개 크기 : 4

타입 : float32

방향 : (4,)


3 x 4로 총 12byte 사용됨 

다음 행으로 갈 때 4byte 띄움

In [25]:
arr1 = np.array([[5,7,9],[1,2,3]], dtype=np.float16) # float16으로 메모리 2칸에 데이터 1개 저장 
# dtype 은 strides 값만 바꿈 

# arr1.data : 넘파이에서 데이터가 들어있는 주소 
# arr1.size : 배열 길이 
# arr1.itemsize : 데이터 하나의 크기 

print(arr1, end = '\n')
print(f'\n데이터 저장 메모리 : {arr1.data}\n')
print(f'원소/요소 개수 : {arr1.size}\n')
print(f'원소/요소 1개 크기 : {arr1.itemsize}\n')
print(f'타입 : {arr1.dtype}\n')
print(f'방향 : {arr1.strides}') # -> 2칸을 띄워야 다음 데이터로 감 


[[5. 7. 9.]
 [1. 2. 3.]]

데이터 저장 메모리 : <memory at 0x0000021943DAAC70>

원소/요소 개수 : 6

원소/요소 1개 크기 : 2

타입 : float16

방향 : (6, 2)


In [26]:
# tensor 생성 
arr_ts = torch.from_numpy(arr1) 
arr_ts

tensor([[5., 7., 9.],
        [1., 2., 3.]], dtype=torch.float16)

as_tensor : 어떨 때는 copy, 어떨 때는 view

tensor : 데이터 copy해서 tensor로 변경 