# Tensor 이해

In [2]:
# 모듈 로딩 
import torch

## 타입 지정 Tensor 클래스 활용
- 데이터 타입 설정 후 생성 
- 데이터 사이즈 설정한 텐서 생성 시 사용
- 데이터의 자료형 변환한 텐서 생성 시 사용 


In [3]:
# 정수형 텐서 생성 
data = [1.4, 2.8, 3.1]

In [6]:
# 1byte 정수형 텐서 생성
data_ts1 = torch.CharTensor(data) # 데이터 타입 지정해서 생성 
data_ts11 = torch.tensor(data, dtype=torch.int8)  # 생성해서 데이터 타입 지정 

print(data_ts1, data_ts11, sep = '\n')

tensor([1, 2, 3], dtype=torch.int8)
tensor([1, 2, 3], dtype=torch.int8)


C:\Users\KDP-35\AppData\Local\Temp\ipykernel_1692\2632023259.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  data_ts1 = torch.CharTensor(data)
C:\Users\KDP-35\AppData\Local\Temp\ipykernel_1692\2632023259.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  data_ts11 = torch.tensor(data, dtype=torch.int8)


입력한 데이터가 실수라서 해당 warning 발생

In [8]:
# 2byte 정수형 텐서 생성
data_ts1 = torch.ShortTensor(data) # 데이터 타입 지정해서 생성 
data_ts11 = torch.tensor(data, dtype=torch.int16)  # 생성해서 데이터 타입 지정 

print(data_ts1, data_ts11, sep = '\n') 

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int16)


C:\Users\KDP-35\AppData\Local\Temp\ipykernel_1692\4156443569.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  data_ts1 = torch.ShortTensor(data)
C:\Users\KDP-35\AppData\Local\Temp\ipykernel_1692\4156443569.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  data_ts11 = torch.tensor(data, dtype=torch.int16)  # 생성해서 데이터 타입 지정


In [10]:
# 논리형 텐서 생성 

data_ts1 = torch.BoolTensor(data) # 데이터 타입 지정해서 생성 
data_ts11 = torch.tensor(data, dtype=torch.bool)  # 생성해서 데이터 타입 지정 

print(data_ts1, data_ts11, sep = '\n')

tensor([True, True, True])
tensor([True, True, True])


0 이거나 비어있으면 False

In [11]:
# 실수형 텐서 생성

data_ts1 = torch.DoubleTensor(data) # 데이터 타입 지정해서 생성 
data_ts11 = torch.tensor(data, dtype=torch.float64)  # 생성해서 데이터 타입 지정 

print(data_ts1, data_ts11, sep = '\n') 

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)


## Tensor 저장 및 실행 위치 설정 ==> 속성 device 설정

In [12]:
# 실행 위치 => CPU / GPU

torch.cuda.is_available()

# GPU에서 수행하는 알고리즘   

False

In [14]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
DEVICE

'cpu'

In [15]:
# 실수형 텐서 생성

data_ts1 = torch.DoubleTensor(data) # 데이터 타입 지정해서 생성 
data_ts11 = torch.tensor(data, dtype=torch.float64, device = DEVICE)  # 생성해서 데이터 타입 지정 

print(data_ts1, data_ts11, sep = '\n') 

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
