# Tensor 저장 구조 이해
- storage 객체
    - 텐서 객체의 메모리 저장 관련 정보 저장 
    - offset : 첫 번째 원소 인덱스 
    - stride : 원소 이동 위한 정보 저장
        - 다음 행 이동하기 위한 메모리 칸 수
        - 다음 열 이동하기 위한 메모리 칸 수

In [1]:
import torch

In [6]:
## 텐서 생성  

data_ts = torch.tensor([[11,22,33],[44,55,66]])
print(data_ts, data_ts.stride(), data_ts.ndim, sep='\n')
# data_ts.stride : 메서드로 () 를 넣으면 볼 수 ㅇ 

tensor([[11, 22, 33],
        [44, 55, 66]])
(3, 1)
2


In [7]:
# STORAGE 정보 => 메모리에 저장된 데이터 형태 1D
data_ts.storage() # 메모리에 저장된 1차원 배열 

C:\Users\KDP-35\AppData\Local\Temp\ipykernel_18084\3544215805.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  data_ts.storage()


 11
 22
 33
 44
 55
 66
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [8]:
print(data_ts.untyped_storage())

 11
 0
 0
 0
 0
 0
 0
 0
 22
 0
 0
 0
 0
 0
 0
 0
 33
 0
 0
 0
 0
 0
 0
 0
 44
 0
 0
 0
 0
 0
 0
 0
 55
 0
 0
 0
 0
 0
 0
 0
 66
 0
 0
 0
 0
 0
 0
 0
[torch.storage.UntypedStorage(device=cpu) of size 48]


In [9]:
data_ts = torch.tensor([[11,22,33],[44,55,66]], dtype = torch.int8) # 위의 데이터를 저장하려면 6byte 필요 => int8
print(data_ts, data_ts.stride(), data_ts.ndim, sep='\n')

tensor([[11, 22, 33],
        [44, 55, 66]], dtype=torch.int8)
(3, 1)
2


In [10]:
print(data_ts.untyped_storage())

 11
 22
 33
 44
 55
 66
[torch.storage.UntypedStorage(device=cpu) of size 6]


In [11]:
data_ts = torch.tensor([[11,22,33],[44,55,66]], dtype = torch.int16) 
print(data_ts, data_ts.stride(), data_ts.ndim, sep='\n')

tensor([[11, 22, 33],
        [44, 55, 66]], dtype=torch.int16)
(3, 1)
2


In [12]:
print(data_ts.untyped_storage())

 11
 0
 22
 0
 33
 0
 44
 0
 55
 0
 66
 0
[torch.storage.UntypedStorage(device=cpu) of size 12]


데이터 1개 저장하는데 2byte 사용 

11에서 22가려면 2칸 (1*2), 11에서 44가려면 6칸 (3*2)

In [17]:
data_ts = torch.tensor([[11,22,33],[44,55,66]], dtype = torch.int8)

In [18]:
mem_storage = data_ts.untyped_storage()
mem_storage[0], mem_storage[-1]

(11, 66)

In [19]:
data_ts.shape, data_ts.dtype

# data_ts.dtype : 바이트 수 알 수 ㅇ 

(torch.Size([2, 3]), torch.int8)

In [20]:
for idx in range(6):
    print(f'[{idx}번째 원소] - {id(mem_storage[idx])}')

# 메모리에 저장된 주소 

[0번째 원소] - 140718571007200
[1번째 원소] - 140718571007552
[2번째 원소] - 140718571007904
[3번째 원소] - 140718571008256
[4번째 원소] - 140718571008608
[5번째 원소] - 140718571008960


In [21]:
for idx in range(6):
    print(f'[{idx}번째 원소] - {(mem_storage[idx])}') # int16 -> 2byte 줘서 0이 끼여서 보임 

[0번째 원소] - 11
[1번째 원소] - 22
[2번째 원소] - 33
[3번째 원소] - 44
[4번째 원소] - 55
[5번째 원소] - 66


In [23]:
for idx in range(6):
    print(f'[{idx}번째 원소] - {id(mem_storage[idx])} : {id(mem_storage[idx])}')

[0번째 원소] - 140718571007200 : 140718571007200
[1번째 원소] - 140718571007552 : 140718571007552
[2번째 원소] - 140718571007904 : 140718571007904
[3번째 원소] - 140718571008256 : 140718571008256
[4번째 원소] - 140718571008608 : 140718571008608
[5번째 원소] - 140718571008960 : 140718571008960


In [24]:
data_ts.data

tensor([[11, 22, 33],
        [44, 55, 66]], dtype=torch.int8)

In [25]:
data_ts.data[0]

tensor([11, 22, 33], dtype=torch.int8)

In [27]:
data_ts.data_ptr() # 실제 데이터가 저장된 주소값 - first element의 주소값

4617291235520

In [28]:
# STORAGE 정보 
print(data_ts.storage(), data_ts.storage_offset())

 11
 22
 33
 44
 55
 66
[torch.storage.TypedStorage(dtype=torch.int8, device=cpu) of size 6] 0


In [32]:
data_ts[1:].storage_offset() # 1행 전체 -> index : 3 

3

In [34]:
data_ts[1,2].storage_offset() # (1,2) -> index : 5

5

In [35]:
data_ts[3:].storage_offset() # 3행 존재하지 x 

6