# Tensor의 모양/형태/shape 변경과 View Tensor

연속성 : 데이터가 메모리에 저장된 모양과 실제 출력되어 보이는 형태가 일치

In [1]:
import torch
import numpy as np

In [2]:
# 텐서 생성
data_ts = torch.arange(1,21)
print(data_ts, data_ts.ndim, data_ts.stride(), sep='\n')

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
1
(1,)


In [3]:
print(data_ts.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


C:\Users\KDP-35\AppData\Local\Temp\ipykernel_10296\1647384617.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(data_ts.storage())


In [4]:
# 1D => 2D 형태/모양/shape 변경 

data_ts2 = data_ts.reshape((-1, 5))
print(data_ts2, data_ts2.ndim, data_ts2.stride(), sep='\n')
print(f'is_contiguous() : {data_ts2.is_contiguous()}') # 연속성 

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
2
(5, 1)
is_contiguous() : True


In [5]:
print(data_ts2.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


In [6]:
data_ts2[0]

tensor([1, 2, 3, 4, 5])

In [7]:
data_ts2[0][0]

tensor(1)

In [8]:
data_ts2[0][0] = 77

In [9]:
data_ts, data_ts2

(tensor([77,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 tensor([[77,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]))

data_ts가 바뀌면 share(view) 한 것이고 안 바뀌면 copy 

-> 상황에 따라 알아서 share(view), copy가 정해짐

In [10]:
data_ts22 = data_ts.reshape((-1,2))
print(data_ts22, data_ts22.ndim, data_ts22.stride(), sep='\n')
print(f'is_contiguous() : {data_ts22.is_contiguous()}') # 연속성 

tensor([[77,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
2
(2, 1)
is_contiguous() : True


In [11]:
data_ts23 = data_ts.reshape((-1,2)).T
data_ts23.is_contiguous()

False

In [12]:
# data_ts23 = torch.arange(1,21).reshape((-1,2)).T
# data_ts23.is_contiguous()

In [13]:
data_ts23

tensor([[77,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [14]:
data_ts23.storage()

 77
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

In [15]:
data_ts23.is_contiguous()

False

In [16]:
## 불연속적 ==> 연속적으로 저장되도록 
data_ts23_c = data_ts23.contiguous()

In [17]:
data_ts23_c.storage() # 새 메모리가 더 생김 

 77
 3
 5
 7
 9
 11
 13
 15
 17
 19
 2
 4
 6
 8
 10
 12
 14
 16
 18
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

In [18]:
data_ts23_c.is_contiguous()

True

In [19]:
data_ts.storage() # data_ts 는 변경 x    

 77
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]