In [1]:
# 모듈 로딩
import torch

## Tensor 생성 [2] torch.rand()

In [2]:
# 0 <= ~ < 1 범위의 임의의 숫자 1개 추출 => rand(*size)
# rand(*size) : 가변인자 => 몇 차원인지 알 수 없음 

torch.manual_seed(1) # 랜덤이지만 seed 고정 

data_ts = torch.rand(1,2,3)
data_ts

tensor([[[0.7576, 0.2793, 0.4031],
         [0.7347, 0.0293, 0.7999]]])

In [3]:
torch.manual_seed(1) 

data_ts = torch.rand(2,2,3) # 2장 
data_ts

tensor([[[0.7576, 0.2793, 0.4031],
         [0.7347, 0.0293, 0.7999]],

        [[0.3971, 0.7544, 0.5695],
         [0.4388, 0.6387, 0.5247]]])

In [7]:
torch.manual_seed(1)

data_ts1 = torch.rand(3)     #  1D vector
data_ts2 = torch.rand(2,3)   #  2D matrix
data_ts3 = torch.rand(2,1,3) #  3D 3d tensor

print(data_ts1, data_ts2, data_ts3, sep='\n\n')

tensor([0.7576, 0.2793, 0.4031])

tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])

tensor([[[0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635]]])


## Tensor 생성 [3] torch.randn()
- 정규분포 형태로 만들어주므로 음수 나올 수 있고 평균이 0, 분산 1 

In [9]:
data_ts1 = torch.randn(3)     #  1D vector
data_ts2 = torch.randn(2,3)   #  2D matrix
data_ts3 = torch.randn(2,1,3) #  3D 3d tensor

print(data_ts1, data_ts2, data_ts3, sep='\n\n')

tensor([0.0996, 0.5727, 1.1492])

tensor([[0.1978, 0.1306, 0.2424],
        [0.8616, 0.0727, 1.3484]])

tensor([[[-0.8737, -0.2693, -0.5124]],

        [[-0.2997,  0.6655,  0.2734]]])


## Tensor 생성 [4] torch.randint()

In [11]:
torch.randint(1,5,(3,5)) # 1 ~ 5까지 3x5

tensor([[1, 3, 2, 4, 4],
        [3, 4, 2, 1, 4],
        [2, 2, 4, 3, 1]])

In [12]:
# 2D vector 
data_ts1 = torch.randint(1,46,(4,6))
data_ts1

tensor([[ 7, 11,  6, 43, 26, 29],
        [41, 36, 25, 20, 18, 16],
        [11, 24, 31, 23, 17, 30],
        [ 3, 30, 30, 44, 15, 38]])