# Tensor 이해 - 형변환

## 방법 [1] type(torch.xxx)

In [1]:
# 모듈 로딩 

import torch

In [2]:
# tensor 생성 
data_ts1 = torch.tensor([1,3,5])
data_ts1, data_ts1.dtype

(tensor([1, 3, 5]), torch.int64)

In [3]:
# int64 -> float
data_ts11 = data_ts1.type(torch.float32)
data_ts11

# 저장하기 위해 변수 생성 

tensor([1., 3., 5.])

In [4]:
data_ts11.dtype

torch.float32

## 방법[2] 타입명()

In [8]:
# int64 -> float
data_ts11 = data_ts1.float()
data_ts11, data_ts11.dtype

(tensor([1., 3., 5.]), torch.float32)

In [9]:
# int64 -> bool
data_ts1.bool()

tensor([True, True, True])

## 방법[3] to(dtype = xxx, device = xxx)

In [10]:
data_ts1.to(dtype=torch.int8)

tensor([1, 3, 5], dtype=torch.int8)

In [13]:
data_ts1_1 = data_ts1.to(dtype=torch.int8, device='cuda' if torch.cuda.is_available() else 'cpu')
data_ts1_1, data_ts1_1.device

(tensor([1, 3, 5], dtype=torch.int8), device(type='cpu'))

In [14]:
data_ts1[0], data_ts1[-1]

(tensor(1), tensor(5))

In [16]:
data_ts1[:2], data_ts1[:-2]

(tensor([1, 3]), tensor([1]))